#include "app/AppBootstrapObjects.h"

#include "appcore/AppRuntimeResolver.h"
#include "app/AppUpdateCheckCoordinator.h"
#include "app/AppUpdateInstallService.h"
#include "app/ApplicationRestartCoordinator.h"
#include "appcore/BackgroundTaskCoordinator.h"
#include "appcore/BackgroundThreadTracker.h"
#include "app/ConfigBackupCoordinator.h"
#include "appcore/CoreDiscoveryService.h"
#include "appcore/CoreProcessCleanupService.h"
#include "app/CoreUpdateCoordinator.h"
#include "app/DefaultServerSwitchCoordinator.h"
#include "app/GeoResourceUpdateCoordinator.h"
#include "appcore/IUserFeedback.h"
#include "appcore/OutboundLocationProbeService.h"
#include "appcore/ProxyRuntimeInterfaces.h"
#include "appcore/ProxySession.h"
#include "domain/models/RuntimeState.h"
#include "app/RuntimeStateSnapshotBuilder.h"
#include "app/ServerCollectionCoordinator.h"
#include "app/ServerEditorCoordinator.h"
#include "app/SettingsApplyCoordinator.h"
#include "app/SettingsWorkflowCoordinator.h"
#include "app/SpeedTestCoordinator.h"
#include "app/SubscriptionWorkflowCoordinator.h"
#include "app/SystemProxyCoordinator.h"
#include "app/TunModeCoordinator.h"
#include "appcore/TunRuntimeService.h"
#include "persistence/JsonConfigRepository.h"
#include "platform/windows/WindowsAutoRunService.h"
#include "platform/windows/WindowsSystemProxyService.h"
#include "runtime/ClientConfigWriter.h"
#include "runtime/QtCoreProcessHost.h"
#include "services/AppUpdateService.h"
#include "services/ConfigBackupService.h"
#include "services/GeoResourceUpdateService.h"
#include "services/RoutingService.h"
#include "services/ServerService.h"
#include "services/SpeedTestController.h"
#include "services/SubscriptionService.h"
#include "ui/mainwindow/MainWindow.h"
#include "ui/tray/TrayController.h"

// Defined out of line because the header only forward declares the member
// types, and std::unique_ptr<T> requires T to be complete where its destructor
// is instantiated.
AppBootstrapObjects::~AppBootstrapObjects() = default;
